### PR TITLE
Added loop to pull all matching issues from Github instead of only one pageful.

### PR DESCRIPTION
**Pull request by RichardWallis**
Added loop to pull all matching issues from Github instead of only one of their pagefuls (100)
Fixes Issue (#4)

### CODE REVIEW

**Comment by RichardWallis** [comment]
Note:  This works when running bin/git2pdf but as a newbie to Ruby I couldn't get 'gem install git2pdf' to update /usr/bin/git2pdf with this new version.

**Comment by jgrau** [comment]
In order for  `gem install git2pdf` to be updated with your changes your PR will have to be merged and then a new release created on rubygems. After that, updating the gem would include your changes. AFAIK :)

**Comment by RichardWallis** [comment]
Also Added new command line option -i to include (Yes|No|Only) Pull Requests in commit de93567

**Comment by RichardWallis** [comment]
Another tweak recognising that some labels include characters that need encoding before sending to to the GitHub API eg:
```bin/git2pdf gen schemaorg/schemaorg  --labels "site tools + python code"```

Is there any enthusiasm to merge this PR and update the release on rubygems as @jgrau explains?

I am finding the capability to output **all** issues/pull requests, and all with a particular label assigned, a very useful option.

**Comment by jgrau** [comment]
Pocketworks, if you would like a maintainer for this library I wouldn't mind taking over...?

**Comment by tobinharris** [comment]
@jgrau Many thanks. I'm not sure why I only just saw this comment now.

Are you still open to being a maintainer?

**Comment by wordswords** [comment]
If @jgrau isn't interested anymore then I would be happy to be a maintainer if needed.

**Comment by jgrau** [comment]
We don't actively use git2pdf anymore (although I could easily see us use it in the future). @wordswords, you seem more interested than me so I would think the project would benefit the most from having you as the maintainer :)

**Comment by tobinharris** [comment]
Thanks David / @wordswords. Ok, that's awesome, thank you. I'll add you to the repo. Feel free to add any credits to the READEME. And also feel free to credit any contributors :)

**Comment by tobinharris** [comment]
Also, let me know when you want me to re-publish the `gem`, I can make sure the latest is out there.

**Comment by tobinharris** [comment]
@wordswords ^^

**Comment by wordswords** [comment]
@tobinharris that's great, thanks! Will let you know when the gem needs to be republished

**Pull request merged**
